version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/html
  nginx-rtmp:
     image: nginx
     ports:
       - "1935:1935"
