version: '3'

services:
  # RTMP server
  nginx-rtmp:
    build:
      context: ./nginx-rtmp
    volumes:
      - ./nginx-rtmp/nginx-rtmp.conf:/etc/nginx/nginx-rtmp.conf
      - ./html/hls-fragments:/hls-fragments
    ports:
      - "1935:1935"

  # nginx for HLS & Flash players & HLS chunks
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/html # Root of HTML data
      - ./le:/le # Let's Encrypt certificates

  # For requesting certs
  certbot:
    image: certbot/certbot
    ports:
      - "80:80"
    volumes:
      - ./le:/etc/letsencrypt

